openapi: 3.0.3
info:
  title: Gate Service API
  version: 1.0.0

paths:
  /students:
    post:
      tags: [students]
      operationId: createStudent
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StudentGateCreateRequest'
      responses:
        '201':
          description: Student created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StudentGateResponse'

  /students/{id}:
    get:
      tags: [students]
      operationId: getStudentById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Student found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StudentGateResponse'
        '404':
          description: Not found

components:
  schemas:
    StudentGateCreateRequest:
      type: object
      required: [fullName, passport]
      properties:
        fullName:
          type: string
        passport:
          type: string

    StudentGateResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
        fullName:
          type: string
        passport:
          type: string